version: '3.5'
services:
    web:
        shm_size: '4gb'
        image: cnet1
        ports:
            - "8000:8000"
        environment:
            DISPLAY: $DISPLAY
            QT_X11_NO_MITSHM: 1
        volumes:
            - .:/app
            - /home/nick/coco:/workspace/coco
            - /home/nick/Загрузки:/workspace/singapore
            - /home/nick/practice2019_/exp/default:/opt/project/exp/default
            - /home/nick/Загрузки/DATASET:/workspace/amedataimages
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ~/.Xauthority:/root/.Xauthority